import type { Metadata } from "next";
import ThemeProvider from "./components/themeProvider";
import "./globals.css";
import Footer from "./layouts/footer";
import Header from "./layouts/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`antialiased`}>
        <ThemeProvider />
        <Header
          itemList={[
            { name: "test-home", src: "/" },
            { name: "test-home", src: "/" },
            { name: "test-home", src: "/" },
          ]}
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
