import { GithubUserResponse } from "../types";

export const MOCKUP_USER: GithubUserResponse = {
  total_count: 1,
  incomplete_results: false,
  items: [
    {
      login: "khil94",
      id: 31910942,
      node_id: "MDQ6VXNlcjMxOTEwOTQy",
      avatar_url: "https://avatars.githubusercontent.com/u/31910942?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/khil94",
      html_url: "https://github.com/khil94",
      followers_url: "https://api.github.com/users/khil94/followers",
      following_url:
        "https://api.github.com/users/khil94/following{/other_user}",
      gists_url: "https://api.github.com/users/khil94/gists{/gist_id}",
      starred_url: "https://api.github.com/users/khil94/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/khil94/subscriptions",
      organizations_url: "https://api.github.com/users/khil94/orgs",
      repos_url: "https://api.github.com/users/khil94/repos",
      events_url: "https://api.github.com/users/khil94/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/khil94/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1,
      bio: "mr.loser",
      location: "seoul",
      name: "김효일",
    },
    {
      login: "khil94",
      id: 31910943,
      node_id: "MDQ6VXNlcjMxOTEwOTQy",
      avatar_url: "https://avatars.githubusercontent.com/u/31910942?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/khil94",
      html_url: "https://github.com/khil94",
      followers_url: "https://api.github.com/users/khil94/followers",
      following_url:
        "https://api.github.com/users/khil94/following{/other_user}",
      gists_url: "https://api.github.com/users/khil94/gists{/gist_id}",
      starred_url: "https://api.github.com/users/khil94/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/khil94/subscriptions",
      organizations_url: "https://api.github.com/users/khil94/orgs",
      repos_url: "https://api.github.com/users/khil94/repos",
      events_url: "https://api.github.com/users/khil94/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/khil94/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1,
      bio: "mr.loser",
      location: "seoul",
      name: "김효일",
    },
    {
      login: "khil94",
      id: 31910944,
      node_id: "MDQ6VXNlcjMxOTEwOTQy",
      avatar_url: "https://avatars.githubusercontent.com/u/31910942?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/khil94",
      html_url: "https://github.com/khil94",
      followers_url: "https://api.github.com/users/khil94/followers",
      following_url:
        "https://api.github.com/users/khil94/following{/other_user}",
      gists_url: "https://api.github.com/users/khil94/gists{/gist_id}",
      starred_url: "https://api.github.com/users/khil94/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/khil94/subscriptions",
      organizations_url: "https://api.github.com/users/khil94/orgs",
      repos_url: "https://api.github.com/users/khil94/repos",
      events_url: "https://api.github.com/users/khil94/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/khil94/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1,
      bio: "mr.loser",
      location: "seoul",
      name: "김효일",
    },
    {
      login: "khil94",
      id: 31910945,
      node_id: "MDQ6VXNlcjMxOTEwOTQy",
      avatar_url: "https://avatars.githubusercontent.com/u/31910942?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/khil94",
      html_url: "https://github.com/khil94",
      followers_url: "https://api.github.com/users/khil94/followers",
      following_url:
        "https://api.github.com/users/khil94/following{/other_user}",
      gists_url: "https://api.github.com/users/khil94/gists{/gist_id}",
      starred_url: "https://api.github.com/users/khil94/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/khil94/subscriptions",
      organizations_url: "https://api.github.com/users/khil94/orgs",
      repos_url: "https://api.github.com/users/khil94/repos",
      events_url: "https://api.github.com/users/khil94/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/khil94/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1,
      bio: "mr.loser",
      location: "seoul",
      name: "김효일",
    },
    {
      login: "khil94",
      id: 31910946,
      node_id: "MDQ6VXNlcjMxOTEwOTQy",
      avatar_url: "https://avatars.githubusercontent.com/u/31910942?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/khil94",
      html_url: "https://github.com/khil94",
      followers_url: "https://api.github.com/users/khil94/followers",
      following_url:
        "https://api.github.com/users/khil94/following{/other_user}",
      gists_url: "https://api.github.com/users/khil94/gists{/gist_id}",
      starred_url: "https://api.github.com/users/khil94/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/khil94/subscriptions",
      organizations_url: "https://api.github.com/users/khil94/orgs",
      repos_url: "https://api.github.com/users/khil94/repos",
      events_url: "https://api.github.com/users/khil94/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/khil94/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1,
      bio: "mr.loser",
      location: "seoul",
      name: "김효일",
    },
  ],
};
